# Generated by Django 3.0.2 on 2020-01-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20)),
                ('rname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baddress', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=20)),
                ('breader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ReaderInfo')),
            ],
            options={
                'db_table': '',
            },
        ),
    ]
